using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Inventory2 : MonoBehaviour
{
    private const int SLOTS = 5;

    private List<IInventoryItem> mItems = new List<IInventoryItem>();

    public event EventHandler<InventoryEventArgs> ItemAdded;

    public void AddItem(IInventoryItem item)
    {
        if(mItems.Count < SLOTS)
        {
            Collider2D collider2D =(item as MonoBehaviour).GetComponent<Collider2D>();
            if (collider2D.enabled)
            {
                collider2D.enabled = false;
                mItems.Add(item);
                item.OnPickup();
                if(ItemAdded  != null)
                {
                    ItemAdded(this, new InventoryEventArgs(item));
                }
            }
        }
    }




    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
